project:
  type: book
  output-dir: _outputs

profile:
  default: html
  group:
    - [html, pdf]

metadata-files:
  - _book-structure.yml

lang: es

book:
  title: "IASI Quarto"
  subtitle: "Guía técnica"
  author: "IASI Project"
  output-file: "iasi-quarto-technical-guide"

format:
  html:
    toc: true
    number-sections: true

  pdf:
    documentclass: scrreprt
    toc: true
    number-sections: true
    colorlinks: false

execute:
  freeze: auto
