format:
  pdf:
    toc: true
    number-sections: true
    include-in-header:
      text: |
        \usepackage{scrlayer-scrpage}
        \clearpairofpagestyles
        \ifoot{\footnotesize © 2026 Javier G. Grandez · IASI Rocks 🤘}
        \cfoot{\footnotesize iasi.quarto 0.10.2}
        \ofoot{\footnotesize \pagemark}
        \pagestyle{scrheadings}
